spring:
  h2:
    console:
      enable: true
    datasource:
      url: dbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: password
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true        #sql format 예쁘게
          highlight_sql: true     #sql 색칠해서
          use_sql_comments: true  #주석으로 부가정보 더 표시
logging:
  level:
    org:
      hibernate:
        SQL: debug